[project]
name = "sysid"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "core",
    "scipy-stubs~=1.18.0",
]

[tool.uv.sources]
core = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
